hats = ["no hat",
"ballin' cap",
"military cover",
"constructing helmet",
"solid bandana",
"canadian mask",
"spas hat",
"the tipper",
"ten gallon",
"king's adornment",
"blue soldier aviator",
"goldilocks",
"raggy rag",
"protector",
"suffocator",
"the entertainer",
"mrowr ears",
"samurai sunhat",
"facial cover",
"bloody mess",
"twirly bean",
"bro glasses",
"chef hat",
"effed up",
"horny helm",
"cooking pot",
"party hat",
"fez",
"night vision",
"riot helmet",
"wielder's delight",
"sunny hat",
"funny glasses",
"the brunette",
"the boss",
"leather hat",
"sneaky beaky",
"robert's hood",
"oooshanka",
"beer hat",
"duck mask",
"burger boy",
"sombreado",
"the sellout",
"cool backwards hat",
"ass clown wig",
"paper boat",
"the cosmonaut",
"virtualized goggles",
"medical mask",
"tinfoil hat",
"dashing topper",
"conehead",
"stupid magic hat",
"bankroll visor",
"the ol arrow gag",
"santa hat",
"elf ears",
"frostman mask",
"stag antlers",
"hanukkah headband",
"kwanzaa krown"]

store = [
"Steam"
,"Discord"
,"Itch.io"
,"GameJolt"
]

premium = [
    "Free-To-Play",
    "Premium Player"
]